---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: pyLODE
  commands:
  - ls
  - whoami
  - mkdir -p /var/www/def/plot
  - cp plot.ttl /var/www/def/plot
  - git clone https://github.com/RDFLib/pyLODE.git
  - cd pyLODE
  - apt install python3-pip -y
  - pip3 install -r requirements.txt
  - cd src/pylode/bin
  - pwd
  - ./pylode -i ../../../../plot.ttl --css true
  - cd ..
  - cp output_files/* /var/www/def/plot
  - cd /var/www/def/plot
  - mv doc.html index.html

...