---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: pyLODE
  commands:
  - git clone https://github.com/RDFLib/pyLODE.git
  - cd pyLODE
  - apt install python3-pip -y
  - pip3 install -r requirements.txt
  - cd src/pylode/bin
  - ./pylode -i ../../../../test/plot.ttl --css true

...